version: "3.1"
services:
  scheduler:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw
    environment:
      - PYTHONPATH=/usr/local/airflow/plugins/modules
    networks:
      - Ex_V1
      - default

  webserver:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw
    environment:
      - PYTHONPATH=/usr/local/airflow/plugins/modules
    networks:
      - Ex_V1
      - default

  triggerer:
    volumes:
      - ./dbt:/usr/local/airflow/dbt:rw
    environment:
      - PYTHONPATH=/usr/local/airflow/plugins/modules
    networks:
      - default
      - Ex_V1

  postgres:
    ports:
      - 56715:5432
    networks:
      - default

networks:
  Ex_V1:
    name: V1
    external: true