from openai import OpenAI
import pandas as pd
import re

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="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",
)


def readTags():
    '''Read all tags'''
    tags = pd.read_csv('Tags.csv')
    return tags


def gpt(prompt):
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content.strip()


def gptTags(url):
    '''Discover relevant tags'''

    # Import tags
    definedTags = readTags()

    prompt = f""" tags list = {list(definedTags['Tags'])}
    Read the entire content of this website {url} and Check the uploaded file and see if the tags in any of the rows in column A are most relevant to the content of the reviewed website. Pay attention to it’s usage, launched platform and industrial and then Pay attention:  return just the tags and no more things and separate them with ","
    """

    # Request prompt
    response = gpt(prompt)


    # Extract the tags of the list from the string
    tags = response.split(", ")

    # Clean tags
    tags= [i.replace("'", "") for i in tags]

    # Keep 3 most relavent
    tags = tags[0:3]

    # check if tags exist in defined tags
    if set(definedTags).isdisjoint(set(tags)):
        print(tags)
        return tags
    else:
        print("Irrelevant tags reported")
        return None

def gptShortDiscription(url):
    '''Return discription generated by GPT'''

    prompt = f"""
        Create a 150 character SEO-friendly description based on information from all pages of the website including the keyword "AI Tools" at {url}
    """

    # Request prompt
    response = gpt(prompt)
    print(response)

    return response

def gptReview(url):
    '''Generate rivew of target url by GPT'''

    prompt= f"""
    Read the entire content of {url} and write a full SEO Friendly Review of site which contain answers of these questions:[what is this website/app? What is its use?] including key word "AI Tools" and have to minimum 600 words.
    """

    # Request prompt
    response = gpt(prompt)
    print(response)

    return response


